FROM node:lts-alpine as build

WORKDIR /opt/app
COPY . .
RUN cd front && npm run build

FROM nginx:alpine
COPY --from=build ./front/web/ /usr/share/nginx/html/front/

COPY ./web/ /usr/share/nginx/html/
COPY ./web/nginx.conf /etc/nginx/conf.d/default.conf
