FROM python:3.7.4-alpine

RUN apk update && apk add tzdata \
    && rm -f /etc/localtime \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

RUN mkdir -p /opt/app

WORKDIR /opt/app
COPY . .

RUN chmod a+x ./prepare.sh && ./prepare.sh
RUN pip install -r requirements.txt

EXPOSE 5000
CMD ["python", "-m", "back.server"]