FROM nginx:alpine

COPY ./web/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./web/ /usr/share/nginx/html/app/
RUN sed -i '/access_log/c \    access_log \/dev\/null;server_tokens off;' /etc/nginx/nginx.conf
