FROM python:3.7.4

WORKDIR /opt/app
COPY . .

RUN chmod a+x ./prepare.sh && ./prepare.sh
RUN pip install -r requirements.txt

ENV PYTHONUNBUFFERED 1

EXPOSE 5000

ENTRYPOINT ["python", "-m", "back.server"]