FROM node:lts-alpine as build

WORKDIR /app

COPY . .

RUN cd front && npm install && npm run build

FROM nginx:alpine

COPY --from=build /app/front/web /usr/share/nginx/html/
COPY ./front/nginx.conf /etc/nginx/conf.d/default.conf
