FROM node:lts-alpine as build

WORKDIR /opt/app
COPY . .
RUN cd front && npm install && npm run build

FROM nginx:alpine

COPY --from=build /opt/app/front/web/ /usr/share/nginx/html/front/

COPY ./web/ /usr/share/nginx/html/
COPY ./web/nginx.conf /etc/nginx/conf.d/default.conf
