version: '3.7'
services:
    qa:
        image: daocloud.io/quantaxis/qacommunity:latest
        container_name: qacommunity
        networks:
            - qanetwork
        ports:
            - "8888:8888"
            - "81:80"
        env_file: env.env
        volumes:
            - qacode:/home
        restart: always

    qaweb_run:
        image: daocloud.io/quantaxis/qarun:latest
        container_name: qarun
        networks:
            - qanetwork
        ports:
            - "8010:8010"
        env_file: env.env
        restart: always
        command: ['/root/wait_for_it.sh', 'qaeventmq:5672', '--' , "/root/runcelery.sh"]

    qamonitor:
        image: daocloud.io/quantaxis/qa-monitor:latest
        ports:
            - "61209:61209"
            - "61208:61208"
        pid: 'host'
        networks:
            - qanetwork
        restart: always

    qamarketcollector:
        image: daocloud.io/quantaxis/qarealtimecollector:latest
        ports:
            - "8011:8011"
        env_file: env.env
        networks:
            - qanetwork
        restart: always
        command:
            ['/root/QUANTAXIS_RealtimeCollector/docker/wait_for_it.sh', 'qaeventmq:5672', '--' ,'/root/QUANTAXIS_RealtimeCollector/docker/start_collector.sh']

    qatrader:
        image: daocloud.io/quantaxis/qatrader:latest
        ports:
            - "8020:8020"
        env_file: env.env
        command:
            ['/root/QATrader/docker/wait_for_it.sh', 'qaeventmq:5672', '--' ,'qatraderserver']
        networks:
            - qanetwork
        restart: always

volumes:
    qacode:
        external:
            name: qacode
networks:
    qanetwork:
        external: true
